version: '3.8'

services:
  web:
    build: .
    #for production dont use volumes
    # network_mode: "host"      
    # volumes:
    #   - .:/app
    image: ${DOCKERHUB_USERNAME:-nicolasmd}/backyardrails:latest
    ports:
      - "127.0.0.1:3001:3000"
    env_file:
      - .env.${ENV:-production}
    environment:
      TZ: America/New_York
      RAILS_ENV: ${ENV:-production}
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"