version: '3'
services:
  # redis:
    # image: redis:6.2
    # networks:
    #   - app_network
  web:
    build: .
    image: nicolasmd/backyardrails:latest
    ports:
      - "3001:3001"
    #for production dont use volumes
    # network_mode: "host"      
    # volumes:
    #   - .:/app
    # depends_on:
    #   - redis
    env_file:
      - .env.${ENV}
    environment:
      TZ: America/New_York
      RAILS_ENV: ${ENV}
    networks:
      - app_network
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app_network: