default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["RDS_HOST"] %>
  username: <%= ENV["RDS_USERNAME"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  port: 5432

development:
  <<: *default
  database: backyard_app_development

test:
  <<: *default
  database: backyard_app_test

production:
  <<: *default
  database: backyard_app_production
